### ISSUE TITLE
RuntimeError: uvloop does not support Windows at the moment

### ISSUE THREAD

**Issue by talonmeyer** [LinkBenjamin/the-Philbott#17]
While installing requirements.txt: 

RuntimeError: uvloop does not support Windows at the moment

Ideally, clarify the lack of Windows support or add an alternate dependency path.

**Comment by LinkBenjamin** [comment]
Relevant Issue: https://github.com/langchain-ai/langchain/issues/3260

**Comment by LinkBenjamin** [comment]
Based on some other StackOverflow threads, I noticed that uvloop isn't actually a dependency of anything I'm using.  It was installed as a transient dependency but nothing seems to actually depend on it.

I ran 

`pip uninstall uvloop` 

and then I tested with my example files without error.  Maybe give that a try and see if that gets you going?  If it works, I'll remove it from the requirements.txt.
